### ISSUE TITLE
[Problem+Suggestion] important!

### ISSUE THREAD

**Issue by DrPigi** [Fuck-Cubik/Fuck-Cubik#12]
1.problem:
when i import the texture its just ignoring it and stays purple/black, it shows in the texture editor
but i don,t have much to do with it....
2.suggestion:
i have 3 suggestions:
a. add 4 vestors views, i mean that you are able to see from up down, side(right-left) and other side(forward-backword). that alows you easly to do the next suggestion:
b.add the option to change object's dimension(resize) or moving it in the area by dragging it with the mouse + it will be good with this suggestion ^^^
c.show texture on the camera viwe

**Comment by Alexander01998** [comment]
Please only put **one** problem/suggestion into **one** Issue. This makes it much easier to organize problems and suggestions.

1. It says **Import pack**, not **Import texture**. It works fine if you import a pack. Read [this tutorial](https://github.com/Fuck-Cubik/Fuck-Cubik/wiki/Getting-started) for more information.  
2a. No. Fuck Cubik isn't just a Cubik clone, so I don't want to re-implement everything in Cubik.  
2b. You can change the size of an element with the element editor.  
2c. Already implemented.
