### ISSUE TITLE
Problems with 3D items

### ISSUE THREAD

**Issue by casey223** [Fuck-Cubik/Fuck-Cubik#16]
![](http://s24.postimg.org/6hhq7nyv9/halp.png)

### Appple.json
```JSON
{
  "parent": "builtin/generated",
  "textures": {
    "layer0": "blocks/bed_feet_top",
    "layer1": "blocks/furnace_front_off"
  },
  "display": {
    "thirdperson": {
      "rotation": [
        -90,
        0,
        0
      ],
      "translation": [
        0,
        1,
        -3
      ],
      "scale": [
        0.55,
        0.55,
        0.55
      ]
    },
    "firstperson": {
      "rotation": [
        0,
        -135,
        25
      ],
      "translation": [
        0,
        4,
        2
      ],
      "scale": [
        1.7,
        1.7,
        1.7
      ]
    }
  },
  "elements": [
    {
      "from": [
        3.9999999999999996,
        0.0,
        3.9999999999999996
      ],
      "to": [
        12.0,
        8.0,
        12.0
      ],
      "faces": {
        "up": {
          "uv": [
            0,
            0,
            0,
            0
          ],
          "texture": "#layer0"
        },
        "down": {
          "uv": [
            0,
            0,
            0,
            0
          ],
          "texture": "#layer0"
        },
        "north": {
          "uv": [
            0,
            0,
            0,
            0
          ],
          "texture": "#layer0"
        },
        "south": {
          "uv": [
            0,
            0,
            0,
            0
          ],
          "texture": "#layer0"
        },
        "west": {
          "uv": [
            0,
            0,
            0,
            0
          ],
          "texture": "#layer0"
        },
        "east": {
          "uv": [
            0,
            0,
            0,
            0
          ],
          "texture": "#layer0"
        }
      }
    },
    {
      "from": [
        7.5,
        8.0,
        7.5
      ],
      "to": [
        8.5,
        12.5,
        8.5
      ],
      "faces": {
        "up": {
          "uv": [
            12,
            5,
            4,
            5
          ],
          "texture": "#layer1"
        },
        "down": {
          "uv": [
            12,
            5,
            4,
            5
          ],
          "texture": "#layer1"
        },
        "north": {
          "uv": [
            12,
            5,
            4,
            5
          ],
          "texture": "#layer1"
        },
        "south": {
          "uv": [
            12,
            5,
            4,
            5
          ],
          "texture": "#layer1"
        },
        "west": {
          "uv": [
            12,
            5,
            4,
            5
          ],
          "texture": "#layer1"
        },
        "east": {
          "uv": [
            12,
            5,
            4,
            5
          ],
          "texture": "#layer1"
        }
      }
    }
  ]
}
```

Thank you and again sorry for 2 threads in 2 days.

**Comment by Alexander01998** [comment]
I'm not quite sure. I guess items work differently.

**Comment by casey223** [comment]
When I open a sword model from the: "Default 3D" Resource pack "fuck cubik" reads it, so I can ad in a new element, and save, then I go into mine craft and what I edited is on it, so I am not sure.

**Comment by Alexander01998** [comment]
Please post the code for that sword.

**Comment by casey223** [comment]
{
"__comment":"Made by Know2Good, part of the 'Default 3D' resource pack.",
"textures": {
	"stick": "blocks/planks_oak",
	"material": "custom/diamond_transparent",
	"particle":"blocks/planks_oak"
},
"elements":[
	{
		"type":"cube", //Blade main
		"from":[7.5,6.5,7.5],
		"to":[8.5,15.5,8.5],
		"rotation": {"origin": [ 8, 1, 8 ], "axis": "y", "angle": 0 },
		"faces": {
			"down":{"uv":[6,15,7,16],"texture":"#material","cullface":"Know2Good"},
			"up":{"uv":[6,7,7,8],"texture":"#material","cullface":"Know2Good"},
			"north":{"uv":[6,7,7,16],"texture":"#material","cullface":"Know2Good"},
			"south":{"uv":[6,7,7,16],"texture":"#material","cullface":"Know2Good"},
			"west":{"uv":[6,7,7,16],"texture":"#material","cullface":"Know2Good"},
			"east":{"uv":[6,7,7,16],"texture":"#material","cullface":"Know2Good"}
		}
	},
	{
		"type":"cube", //Blade edges
		"from":[7,6.5,7.75],
		"to":[9,15.5,8.25],
		"rotation": {"origin": [ 8, 1, 8 ], "axis": "y", "angle": 0 },
		"faces": {
			"down":{"uv":[6,14,7,15],"texture":"#material","cullface":"Know2Good"},
			"up":{"uv":[6,6,7,7],"texture":"#material","cullface":"Know2Good"},
			"north":{"uv":[6,6,7,15],"texture":"#material","cullface":"Know2Good"},
			"south":{"uv":[6,6,7,15],"texture":"#material","cullface":"Know2Good"},
			"west":{"uv":[6,6,7,15],"texture":"#material","cullface":"Know2Good"},
			"east":{"uv":[6,6,7,15],"texture":"#material","cullface":"Know2Good"}
		}
	},
	{
		"type":"cube", //Blade point
		"from":[7.75,15.5,7.5],
		"to":[8.25,16.5,8.5],
		"rotation": {"origin": [ 8, 1, 8 ], "axis": "y", "angle": 0 },
		"faces": {
			"down":{"uv":[0,0,1,1],"texture":"#material","cullface":"Know2Good"},
			"up":{"uv":[0,0,1,1],"texture":"#material","cullface":"Know2Good"},
			"north":{"uv":[0,0,1,1],"texture":"#material","cullface":"Know2Good"},
			"south":{"uv":[0,0,1,1],"texture":"#material","cullface":"Know2Good"},
			"west":{"uv":[0,0,1,1],"texture":"#material","cullface":"Know2Good"},
			"east":{"uv":[0,0,1,1],"texture":"#material","cullface":"Know2Good"}
		}
	},
	{
		"type":"cube", //Blade point
		"from":[7.5,15.5,7.75],
		"to":[8.5,16.5,8.25],
		"rotation": {"origin": [ 8, 1, 8 ], "axis": "y", "angle": 0 },
		"faces": {
			"down":{"uv":[0,0,1,1],"texture":"#material","cullface":"Know2Good"},
			"up":{"uv":[0,0,1,1],"texture":"#material","cullface":"Know2Good"},
			"north":{"uv":[0,0,1,1],"texture":"#material","cullface":"Know2Good"},
			"south":{"uv":[0,0,1,1],"texture":"#material","cullface":"Know2Good"},
			"west":{"uv":[0,0,1,1],"texture":"#material","cullface":"Know2Good"},
			"east":{"uv":[0,0,1,1],"texture":"#material","cullface":"Know2Good"}
		}
	},
	{
		"type":"cube", //Blade point
		"from":[7.75,16.5,7.75],
		"to":[8.25,17,8.25],
		"rotation": {"origin": [ 8, 1, 8 ], "axis": "y", "angle": 0 },
		"faces": {
			"down":{"uv":[2,8,3,9],"texture":"#material","cullface":"Know2Good"},
			"up":{"uv":[2,8,3,9],"texture":"#material","cullface":"Know2Good"},
			"north":{"uv":[2,8,3,9],"texture":"#material","cullface":"Know2Good"},
			"south":{"uv":[2,8,3,9],"texture":"#material","cullface":"Know2Good"},
			"west":{"uv":[2,8,3,9],"texture":"#material","cullface":"Know2Good"},
			"east":{"uv":[2,8,3,9],"texture":"#material","cullface":"Know2Good"}
		}
	},
	{
		"type":"cube", //Guard east 
		"from":[9.5,6,7.25],
		"to":[10.75,7,8.75],
		"rotation": {"origin": [ 8, 1, 8 ], "axis": "y", "angle": 0 },
		"faces": {
			"down":{"uv":[6,2,7,3],"texture":"#material","cullface":"Know2Good"},
			"up":{"uv":[6,2,7,3],"texture":"#material","cullface":"Know2Good"},
			"north":{"uv":[6,2,7,3],"texture":"#material","cullface":"Know2Good"},
			"south":{"uv":[6,2,7,3],"texture":"#material","cullface":"Know2Good"},
			"west":{"uv":[6,2,7,3],"texture":"#material","cullface":"Know2Good"},
			"east":{"uv":[6,2,7,3],"texture":"#material","cullface":"Know2Good"}
		}
	},
	{
		"type":"cube", //Guard middle 
		"from":[6.5,5.5,7],
		"to":[9.5,6.5,9],
		"rotation": {"origin": [ 8, 1, 8 ], "axis": "y", "angle": 0 },
		"faces": {
			"down":{"uv":[3,2,6,3],"texture":"#material","cullface":"Know2Good"},
			"up":{"uv":[3,2,6,3],"texture":"#material","cullface":"Know2Good"},
			"north":{"uv":[3,2,6,3],"texture":"#material","cullface":"Know2Good","rotation": 180},
			"south":{"uv":[3,2,6,3],"texture":"#material","cullface":"Know2Good"},
			"west":{"uv":[3,2,4,3],"texture":"#material","cullface":"Know2Good","rotation": 270},
			"east":{"uv":[5,2,6,3],"texture":"#material","cullface":"Know2Good","rotation": 90}
		}
	},
	{
		"type":"cube", //Guard west 
		"from":[5.25,6,7.25],
		"to":[6.5,7,8.75],
		"rotation": {"origin": [ 8, 1, 8 ], "axis": "y", "angle": 0 },
		"faces": {
			"down":{"uv":[2,2,3,3],"texture":"#material","cullface":"Know2Good"},
			"up":{"uv":[2,2,3,3],"texture":"#material","cullface":"Know2Good"},
			"north":{"uv":[2,2,3,3],"texture":"#material","cullface":"Know2Good"},
			"south":{"uv":[2,2,3,3],"texture":"#material","cullface":"Know2Good"},
			"west":{"uv":[2,2,3,3],"texture":"#material","cullface":"Know2Good"},
			"east":{"uv":[2,2,3,3],"texture":"#material","cullface":"Know2Good"}
		}
	},
	{
		"type":"cube", //Pommel 
		"from":[7.25,0.75,7.25],
		"to":[8.75,2.25,8.75],
		"rotation": {"origin": [ 8, 1, 8 ], "axis": "y", "angle": 0 },
		"faces": {
			"down":{"uv":[3,2,4,3],"texture":"#material","cullface":"Know2Good"},
			"up":{"uv":[3,2,4,3],"texture":"#material","cullface":"Know2Good"},
			"north":{"uv":[3,2,4,3],"texture":"#material","cullface":"Know2Good","rotation": 180},
			"south":{"uv":[3,2,4,3],"texture":"#material","cullface":"Know2Good"},
			"west":{"uv":[3,2,4,3],"texture":"#material","cullface":"Know2Good","rotation": 270},
			"east":{"uv":[3,2,4,3],"texture":"#material","cullface":"Know2Good","rotation": 90}
		}
	},
	{
		"type":"cube", //Stick
		"from":[7.5,2,7.5],
		"to":[8.5,6,8.5],
		"rotation": {"origin": [ 8, 1, 8 ], "axis": "y", "angle": 0 },
		"faces": {
			"down":{"uv":[4,15,5,16],"texture":"#stick","cullface":"Know2Good"},
			"up":{"uv":[7,15,8,16],"texture":"#stick","cullface":"Know2Good"},
			"north":{"uv":[4,15,8,16],"texture":"#stick","cullface":"Know2Good","rotation":90},
			"south":{"uv":[4,15,8,16],"texture":"#stick","cullface":"Know2Good","rotation":90},
			"west":{"uv":[4,15,8,16],"texture":"#stick","cullface":"Know2Good","rotation":90},
			"east":{"uv":[4,15,8,16],"texture":"#stick","cullface":"Know2Good","rotation":90}
		}
	}
],
"display": {
	"thirdperson": {
		"rotation": [ 10, 90, 270 ],
		"translation": [ 0, 1, -3 ],
		"scale": [ 1, 1, 1 ]
	},
	"firstperson": {
		"rotation": [ 0, -135, 0 ],
		"translation": [ -2, 4, 2 ],
		"scale": [ 1.7, 1.7, 1.7 ]
	},
	"gui": {
		"rotation": [ 0, 0, 0 ],
		"translation": [ 0, -1, 0 ],
		"scale": [ 1.9, 1.6, 1.9 ]
	}
}
}

**Comment by Alexander01998** [comment]
`"parent": "builtin/generated"` caused the problem. It works fine without it:

![screenshot](https://cloud.githubusercontent.com/assets/10100202/5664153/5d15a652-974e-11e4-8a98-dc9fed0d19ca.png)

```JSON
{
  "textures": {
    "layer0": "blocks/bed_feet_top",
    "layer1": "blocks/furnace_front_off"
  },
  "display": {
    "thirdperson": {
      "rotation": [
        -90,
        0,
        0
      ],
      "translation": [
        0,
        1,
        -3
      ],
      "scale": [
        0.55,
        0.55,
        0.55
      ]
    },
    "firstperson": {
      "rotation": [
        0,
        -135,
        25
      ],
      "translation": [
        0,
        4,
        2
      ],
      "scale": [
        1.7,
        1.7,
        1.7
      ]
    }
  },
  "elements": [
    {
      "from": [
        3.9999999999999996,
        0.0,
        3.9999999999999996
      ],
      "to": [
        12.0,
        8.0,
        12.0
      ],
      "faces": {
        "up": {
          "uv": [
            0,
            0,
            0,
            0
          ],
          "texture": "#layer0"
        },
        "down": {
          "uv": [
            0,
            0,
            0,
            0
          ],
          "texture": "#layer0"
        },
        "north": {
          "uv": [
            0,
            0,
            0,
            0
          ],
          "texture": "#layer0"
        },
        "south": {
          "uv": [
            0,
            0,
            0,
            0
          ],
          "texture": "#layer0"
        },
        "west": {
          "uv": [
            0,
            0,
            0,
            0
          ],
          "texture": "#layer0"
        },
        "east": {
          "uv": [
            0,
            0,
            0,
            0
          ],
          "texture": "#layer0"
        }
      }
    },
    {
      "from": [
        7.5,
        8.0,
        7.5
      ],
      "to": [
        8.5,
        12.5,
        8.5
      ],
      "faces": {
        "up": {
          "uv": [
            12,
            5,
            4,
            5
          ],
          "texture": "#layer1"
        },
        "down": {
          "uv": [
            12,
            5,
            4,
            5
          ],
          "texture": "#layer1"
        },
        "north": {
          "uv": [
            12,
            5,
            4,
            5
          ],
          "texture": "#layer1"
        },
        "south": {
          "uv": [
            12,
            5,
            4,
            5
          ],
          "texture": "#layer1"
        },
        "west": {
          "uv": [
            12,
            5,
            4,
            5
          ],
          "texture": "#layer1"
        },
        "east": {
          "uv": [
            12,
            5,
            4,
            5
          ],
          "texture": "#layer1"
        }
      }
    }
  ]
}
```

**Comment by casey223** [comment]
Thank you for solving this
