### ISSUE TITLE
Google Analytics tracking (with an option to disable it)

### ISSUE THREAD

**Issue by Alexander01998** [Fuck-Cubik/Fuck-Cubik#19]

**Comment by casey223** [comment]
When can we expect a release?

**Comment by Alexander01998** [comment]
@casey223 When it's finished. If you can't wait for the release, you can download the latest source code and compile it.

**Comment by casey223** [comment]
Ok, how would I go about doing that?

**Comment by Alexander01998** [comment]
@casey223 You can do that with [Eclipse](http://www.eclipse.org):
1. Create a new java project (`New>Java Project`) and set the JRE to *JavaSE-1.7*.
2. Place the downloaded source code inside of the project or synchronize it with the Git Repository (`Team>Share Project...`).
3. Add the required libraries (`Build Path>Configure Build Path...`).
4. Export the project into a runnable JAR file (`Export...`).

Fuck Cubik's libraries:
* gson-2.3.1.jar
* lwjgl.jar
* lwjgl_util.jar
* slick.jar

If you are not familiar with Eclipse, there are plenty of tutorials out there. Just google it.

**Comment by casey223** [comment]
i am familiar just getting back int java coding havent done it since beta 1.8.1
