### ISSUE TITLE
how to use fuck cubik?

### ISSUE THREAD

**Issue by OMGchangeMYusername** [Fuck-Cubik/Fuck-Cubik#22]
you know i really love the idea of custom resource packs and being able to create your own!
and i downloaded fuck cubik hoping that it's a bit easier to use..
but i was a total noob at these things so can you please make a tutorial on how to use it?
you can make a tutorial about the TNT model you made :3
we'd really love that!

**Comment by Alexander01998** [comment]
Did you read the [Getting started guide](https://github.com/Fuck-Cubik/Fuck-Cubik/wiki/Getting-started)?

**Comment by OMGchangeMYusername** [comment]
yes.but i want to know how to make the textures and stuff!
is it like the same way of making normal resource packs?
(although i don't think it is that easy) 
i guess making a tutorial on the TNT model will be much better to learn :)

**Comment by Alexander01998** [comment]
> but i want to know how to make the textures and stuff!

*Making* textures is not a part of Fuck Cubik. It can only *make* 3D models and *add* existing textures to them.

You can make your own textures with PhotoShop or something like that.

> i guess making a tutorial on the TNT model will be much better to learn :)

The TNT model is too complex for a tutorial (it has 63 elements). It should be something more simple, like the brown mushroom.

**Comment by Alexander01998** [comment]
There you go: https://github.com/Fuck-Cubik/Fuck-Cubik/wiki/Your-first-3D-model
