### ISSUE TITLE
Making A Wiki?

### ISSUE THREAD

**Issue by casey223** [Fuck-Cubik/Fuck-Cubik#23]
would you like me to create a wiki based on this to help people make models and other things

**Comment by Alexander01998** [comment]
What do you mean?

The Fuck Cubik wiki is [here](https://github.com/Fuck-Cubik/Fuck-Cubik/wiki) and the how to make a model tutorial is [here](https://github.com/Fuck-Cubik/Fuck-Cubik/wiki/Your-first-3D-model).

**Comment by casey223** [comment]
i mean something like this http://fcubik.wikia.com/wiki/FCubik_Wiki

**Comment by Alexander01998** [comment]
> i mean something like this http://fcubik.wikia.com/wiki/FCubik_Wiki

Then the answer is no. I have a wiki and I don't want a second one. Especially not a second one that I have no control over.

**Comment by casey223** [comment]
Ah ok

**Comment by casey223** [comment]
Want me to take it down?

**Comment by Alexander01998** [comment]
Yes, that would be nice.
