### ISSUE TITLE
Followed the tutorial and got stuck after that

### ISSUE THREAD

**Issue by yopapi** [Fuck-Cubik/Fuck-Cubik#24]
brothe i need some help with this shit, can u like make a video how to use it or explain it a lil better

**Comment by yopapi** [comment]
i followed everything u did with the bread thing but im stuck after that

**Comment by Alexander01998** [comment]
> i followed everything u did with the bread thing but im stuck after that

What do you mean by "after that"? The tutorial briefly covers pretty much every feature in Fuck Cubik, so there isn't much "after that" to get stuck with.
