### ISSUE TITLE
Opening files

### ISSUE THREAD

**Issue by JumpyNinja01** [Fuck-Cubik/Fuck-Cubik#25]
Hi, so im new to this stuff, i checked out the bread tutorial thing and i thought it was pretty cool. the problem i am having is how and where do you navigate to open a texture or whatever? i am trying to make the texture for an apple (might try the bread one) however i don't know how to open the apple texture, i cannot navigate into my texture pack or versions folder  thingy because it will only view certain files (JSON 3d Model files [not sure what that is]) please help me, thanks :D

**Comment by Alexander01998** [comment]
Fuck Cubik can only edit JSON 3D models and add existing textures to them.

You can use a third party image editor to make your own textures and then use Fuck Cubik to add them to a 3D model.

**Comment by JumpyNinja01** [comment]
Okay, so lets say i made an apple texture then, how do i put that into fuck-Cubik? i can use the software, however i dont know how to import a texture into Fuck-Cubik. there should be a video tutorial or something on this...

**Comment by JumpyNinja01** [comment]
Because, what it looks like you are saying to me i that i need to make a 3d model to be sble to create a 3d model in Fuck-Cubik which to me makes no sense

**Comment by OMGchangeMYusername** [comment]
I think there should be some sort of video tutorial too :+1:

**Comment by Alexander01998** [comment]
> what it looks like you are saying to me is that i need to make a 3d model to be able to create a 3d model

Please remember that 3D models and textures are entirely different things.
